on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: w00ea933.kasserver.com
          username: f017176b
          password: ${{ secrets.ftp_password }}
          local-dir: "./_site"
          server-dir: "/blog"
